name: Deploy Laravel to IONOS via SFTP (lftp)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer

      - name: Install Composer deps (prod)
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          mkdir -p storage/framework/{cache,sessions,views}
          mkdir -p bootstrap/cache
          rm -f bootstrap/cache/*.php || true

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via lftp mirror (SFTP)
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          USERNAME: ${{ secrets.SFTP_USERNAME }}
          PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          lftp -u "${USERNAME},${PASSWORD}" sftp://$HOST << 'EOF'
          set sftp:auto-confirm yes
          set net:max-retries 2
          set net:timeout 20
          set net:reconnect-interval-base 5
          # push local -> remote (mirror -R)
          mirror -R \
            --parallel=4 \
            --verbose \
            --exclude-glob .git* \
            --exclude-glob .github/* \
            --exclude-glob node_modules/* \
            --exclude-glob tests/* \
            --exclude-glob vendor/bin/* \
            --exclude-glob storage/logs/* \
            --exclude-glob storage/framework/cache/* \
            --exclude-glob storage/framework/sessions/* \
            --exclude-glob storage/framework/views/* \
            ./ ${REMOTE_PATH}
          bye
          EOF
