name: Deploy Laravel to IONOS via SFTP

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Composer deps (prod)
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          mkdir -p storage/framework/{cache,sessions,views}
          mkdir -p bootstrap/cache
          rm -f bootstrap/cache/*.php || true

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4   # <- exact casing & pinned version
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: sftp
          port: 22
          local-dir: ./
          server-dir: ${{ secrets.REMOTE_PATH }}
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            tests/**
            vendor/bin/**
            storage/logs/**
            storage/framework/cache/**
            storage/framework/sessions/**
            storage/framework/views/**
           
