name: Deploy to IONOS via SFTP (no mkdir, no target)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via SFTP to current remote dir
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          USERNAME: ${{ secrets.SFTP_USERNAME }}
          PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          lftp -u "${USERNAME},${PASSWORD}" sftp://${HOST} <<EOF
          set sftp:auto-confirm yes
          set net:max-retries 2
          set net:timeout 30
          set net:reconnect-interval-base 5
          set xfer:use-temp-file yes
          set cmd:fail-exit yes

          # Upload LOCAL repo root into the CURRENT REMOTE DIR (no target arg, so no extra folder)
          mirror -R \
            --verbose \
            --parallel=4 \
            --no-perms \
            --exclude-glob .git* \
            --exclude-glob .github/* \
            --exclude-glob node_modules/* \
            --exclude-glob tests/* \
            --exclude-glob storage/logs/* \
            --exclude-glob storage/framework/cache/* \
            --exclude-glob storage/framework/sessions/* \
            --exclude-glob storage/framework/views/* \
            --exclude-glob docker/* \
            --exclude-glob docker-compose*.yml \
            --exclude-glob .env \
            --exclude-glob .env.* \
            ./

          bye
          EOF
